<?php

require "../includes/auth.php";
require "../database/database.php";

if ($_SERVER["REQUEST_METHOD"] !== "POST") {
    header("Location: ../staff.php");
    exit;
}

$role            = $_POST["role"] ?? "";
$password        = $_POST["password"] ?? "";
$confirmPassword = $_POST["confirm_password"] ?? "";

function back_with_error(string $message): never
{
    header("Location: ../staff.php?error=" . urlencode($message));
    exit;
}

if (!in_array($role, ["reader", "plumber", "admin"], true)) {
    back_with_error("Please choose a valid role.");
}

if (strlen($password) < 6) {
    back_with_error("Password must be at least 6 characters.");
}

if ($password !== $confirmPassword) {
    back_with_error("Passwords do not match.");
}

try {

    // user_code is generated by the database trigger (SVOB-READ-..., SVOB-PLUM-..., SVOB-ADMIN-...)
    $stmt = $pdo->prepare("
        INSERT INTO users (role, password)
        VALUES (:role, :password)
        RETURNING user_code
    ");

    $stmt->execute([
        ":role"     => $role,
        ":password" => $password,
    ]);

    $userCode = $stmt->fetchColumn();

    if (!$userCode) {
        back_with_error("Failed to generate user code.");
    }

    header("Location: ../staff.php?created=" . urlencode($userCode) . "&role_added=" . urlencode($role));
    exit;

} catch (PDOException $e) {
    back_with_error("Database error: " . $e->getMessage());
}
